hyperskill_project:
  id: 8
  ide_files: https://stepik.org/media/attachments/lesson/254284/additional_files.json
  is_template_based: false
  use_ide: true
stages:
- id: 46
  step: 7686
  is_completed: true
- id: 47
  step: 7687
  is_completed: true
- id: 48
  step: 7688
  is_completed: true
- id: 49
  step: 7689
  is_completed: true
- id: 469
  step: 7690
  is_completed: true
topics:
  0:
  - title: Units of information
    theory_id: 6865
  - title: Introduction to Kotlin
    theory_id: 4350
  - title: Basic literals
    theory_id: 4351
  - title: Overview of the basic program
    theory_id: 4362
  - title: Values and variables
    theory_id: 4371
  - title: Data types
    theory_id: 4388
  - title: The classification of basic types
    theory_id: 4455
  - title: Standard output
    theory_id: 4425
  - title: Arithmetic operations
    theory_id: 4472
  - title: Boolean and logical operations
    theory_id: 4515
  - title: Invoking functions
    theory_id: 4575
  - title: Standard input
    theory_id: 4445
  - title: Type conversion
    theory_id: 4672
  - title: Type inference
    theory_id: 9506
  - title: Integers in action
    theory_id: 4488
  - title: Relational operators
    theory_id: 4525
  - title: Characters
    theory_id: 4680
  - title: Ranges
    theory_id: 4633
  - title: Strings
    theory_id: 4540
  - title: Arrays
    theory_id: 4564
  - title: If expression
    theory_id: 4625
  - title: Repeating blocks
    theory_id: 4643
  - title: For loop and ranges
    theory_id: 4652
  - title: For loop and arrays
    theory_id: 4657
  1:
  - title: Comments
    theory_id: 4406
  - title: Coding style conventions
    theory_id: 4419
  - title: Naming variables
    theory_id: 4389
  - title: IDE
    theory_id: 3805
  - title: IntelliJ IDEA
    theory_id: 3801
  - title: IDEA Basics
    theory_id: 5819
  - title: EduTools
    theory_id: 5839
  2:
  - title: Introduction to OOP
    theory_id: 3614
  - title: Declaring functions
    theory_id: 4580
  - title: Objects
    theory_id: 6773
  - title: String templates
    theory_id: 4547
  - title: Declaring classes
    theory_id: 6200
  - title: Constructors
    theory_id: 6237
  - title: Member functions
    theory_id: 6364
  - title: Extension functions
    theory_id: 6621
  - title: Properties accessors
    theory_id: 10511
  3:
  - title: Object declarations
    theory_id: 9364
  - title: Enum
    theory_id: 6245
